config/routes.rb
Rails.application.routes.draw do
  resources :rounds
  resources :invoices
  get '/invoices/:id/download', action: 'download', controller: 'invoices', defaults: { format: :csv }
  resources :categories
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :cycles
  resources :orders
  put '/orders/:id/items', action: 'add', controller: 'orders'
  delete '/orders/:id/items/:item_id', action: 'remove', controller: 'orders'
  resources :providers
  resources :products
  put '/users/:id/make_admin', action: 'make_admin', controller: 'users'
  put '/users/:id/validate', action: 'validate', controller: 'users'
  put '/users/reset_validation', action: 'reset_validation', controller: 'users'
  resources :users
  root 'homepage#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :round
  belongs_to :user
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  require 'csv'

  include Utils

  before_action :authenticate_user!
  before_action :is_admin
  before_action :set_invoice, only: %i[ show edit update destroy download ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  def download
    # csv = CSV.new(@invoice.csv)
    respond_to do |format|
      format.csv { send_data @invoice.csv, filename: "invoice-#{@invoice.id}.csv" }
    end
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    @invoice.user = current_user

    total_products = {}

    @invoice.round.orders.where(submitted: true).each do |order|
      @invoice.total += order.total
      order.order_items.each do |item|
        unless total_products.key?(item.product.id)
          total_products[item.product.id] = { product_id: item.product.id,
                                              product_name: item.product.name,
                                              product_quantity: 0,
                                              product_unit: item.product.unit,
                                              conditioning_id: nil,
                                              conditioning_cat_nb: nil,
                                              conditioning_name: nil,
                                              conditioning_quantity: nil,
                                              total_cost: nil
                                            }
        end
        total_products[item.product.id][:product_quantity] += item.quantity
        selected_conditioning = item.product.conditionings.first
        if item.product.conditionings.count > 1
          item.product.conditionings.each do |conditioning|
            if total_products[item.product.id][:product_quantity] > conditioning.quantity and selected_conditioning.quantity < conditioning.quantity
              selected_conditioning = conditioning
            end
          end
        end
        total_products[item.product.id][:conditioning_id] = selected_conditioning.id
        total_products[item.product.id][:conditioning_cat_nb] = selected_conditioning.cat_nb
        total_products[item.product.id][:conditioning_name] = selected_conditioning.name
        total_products[item.product.id][:conditioning_quantity] = (total_products[item.product.id][:product_quantity] / selected_conditioning.quantity).ceil
        total_products[item.product.id][:total_cost] = selected_conditioning.price * total_products[item.product.id][:conditioning_quantity]
      end
    end

    csv_file = ""
    line = "%d,%s,%f,%s,%d,%s,%s,%f\n"

    csv_file += "product_id,product_name,product_quantity,product_unit,conditioning_id,conditioning_cat_nb,conditioning_name,conditioning_quantity\n"
    total_products.each do |key, item|
      csv_file += line % [item[:product_id],item[:product_name],item[:product_quantity],item[:product_unit],item[:conditioning_id],item[:conditioning_cat_nb],item[:conditioning_name],item[:conditioning_quantity]]
    end

    @invoice.csv = csv_file

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    render(:file => Rails.root.join('public', '403'), :formats => [:html], :status => 403, :layout => false)
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:round_id)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, html: {class: "form-admin"}) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-label-group">
    <%= form.label :round %><br />
    <%= form.collection_select :round_id, Round.order(:id), :id, :start_at, {}, {:class => "custom-select d-block w-100"} %>
  </div>

  <div class="actions">
    <%= form.submit(class: "btn btn-lg btn-primary btn-block") %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t :invoices %></h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= t :created_at %></th>
      <th scope="col"><%= t :user %></th>
      <th scope="col"><%= t :round %></th>
      <th scope="col"><%= t :total %></th>
      <th scope="col"><%= t :CSV %></th>
      <th scope="col"><%= t :actions %></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.id %></td>
        <td><%= invoice.created_at %></td>
        <td><%= link_to invoice.user.name, invoice.user %></td>
        <td><%= link_to invoice.round.id, invoice.round %></td>
        <td><%= invoice.total %></td>
        <td><%= link_to I18n.t(:download), "/invoices/#{invoice.id}/download" %></td>
        <td><%= link_to 'Show', invoice %> | <%= link_to 'Edit', edit_invoice_path(invoice) %> | <%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>