config/routes.rb
Rails.application.routes.draw do
  resources :rounds
  resources :invoices
  get '/invoices/:id/download', action: 'download', controller: 'invoices', defaults: { format: :csv }
  resources :categories
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :cycles
  resources :orders
  put '/orders/:id/items', action: 'add', controller: 'orders'
  delete '/orders/:id/items/:item_id', action: 'remove', controller: 'orders'
  resources :providers
  resources :products
  put '/users/:id/make_admin', action: 'make_admin', controller: 'users'
  put '/users/:id/validate', action: 'validate', controller: 'users'
  put '/users/reset_validation', action: 'reset_validation', controller: 'users'
  resources :users
  root 'homepage#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         # :confirmable


  has_many :orders, :dependent => :destroy

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end

  def name
    first_name + " " + last_name
  end

  def is_admin
    if self.has_role? :admin
      true
    else
      false
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    if User.count == 1
      User.first.add_role(:admin)
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Utils

  before_action :authenticate_user!
  before_action :set_user, only: %i[ show edit update destroy make_admin validate]
  before_action :is_admin, only: %i[ index make_admin validate reset_validation]
  before_action :is_self, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.order('id DESC').all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def validate
    unless @user.validated
      @user.validated = true
      @user.validated_by = current_user.first_name + " " + current_user.last_name
      @user.validated_at = Time.now
    else
      @user.validated = false
      @user.validated_by = current_user.first_name + " " + current_user.last_name
      @user.validated_at = Time.now
    end
    if @user.save
      respond_to do |format|
        format.html { redirect_to request.referrer, notice: I18n.t(:validated_status_changed) }
      end
    end
  end

  def reset_validation
    for user in User.all
      user.validated = false
      user.validated_by = ""
      user.validated_at = nil
      user.save
    end
  end

  def make_admin
    unless @user.has_role? :admin
      @user.add_role :admin
    else
      @user.remove_role :admin
    end
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: I18n.t(:admin_status_changed) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def is_self
      unless current_user.email == @user.email or current_user.has_role?(:admin)
        render(:file => Rails.root.join('public', '403'), :formats => [:html], :status => 403, :layout => false)
      end
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :phone)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, html: {class: "form-admin"}) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-label-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", type: "email", class: "form-control", placeholder: I18n.t(:email_placeholder), required: true %>
  </div>

  <div class="form-label-group">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "form-control", placeholder: I18n.t(:first_name_placeholder), required: true %>
  </div>

  <div class="form-label-group">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "form-control", placeholder: I18n.t(:last_name_placeholder), required: true %>
  </div>

  <div class="form-label-group">
    <%= f.label :phone %><br />
    <%= f.telephone_field :phone, autofocus: true, autocomplete: "phone", class: "form-control", placeholder: I18n.t(:phone_placeholder), required: true %>
  </div>

  <div class="actions">
    <%= f.submit(class: "btn btn-lg btn-primary btn-block") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= t :user_edit_title%></h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t :users %></h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= t :first_name %></th>
      <th scope="col"><%= t :last_name %></th>
      <th scope="col"><%= t :phone %></th>
      <th scope="col"><%= t :email %></th>
      <th scope="col"><%= t :validated %></th>
      <th scope="col"><%= t :admin %></th>
      <th scope="col"><%= t :actions %></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td>
          <% if user.validated %>
            <%= t :yes %> | <%= link_to I18n.t(:remove_validation), "/users/"+user.id.to_s+"/validate", method: :put, data: { confirm: I18n.t(:sure_question) } %>
          <% else %>
            <%= t :no %> | <%= link_to I18n.t(:validate), "/users/"+user.id.to_s+"/validate", method: :put, data: { confirm: I18n.t(:sure_question) } %>
          <% end %>
        </td>
        <td>
          <% if user.has_role? :admin %>
            <%= t :yes %> | <%= link_to I18n.t(:remove_admin), "/users/"+user.id.to_s+"/make_admin", method: :put, data: { confirm: I18n.t(:sure_question) } %>
          <% else %>
            <%= t :no %> | <%= link_to I18n.t(:make_admin), "/users/"+user.id.to_s+"/make_admin", method: :put, data: { confirm: I18n.t(:sure_question) } %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %> | <%= link_to 'Edit', edit_user_path(user) %> | <%= link_to 'Destroy', user, method: :delete, data: { confirm: I18n.t(:sure_question) } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to I18n.t(:new_user), new_user_path %> | <%= link_to I18n.t(:reset_validation), "/users/reset_validation", method: :put, data: { confirm: I18n.t(:sure_question) } %>

app/views/users/new.html.erb
<h1><%= t :new_user %></h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>