config/routes.rb
Rails.application.routes.draw do
  resources :rounds
  resources :invoices
  get '/invoices/:id/download', action: 'download', controller: 'invoices', defaults: { format: :csv }
  resources :categories
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :cycles
  resources :orders
  put '/orders/:id/items', action: 'add', controller: 'orders'
  delete '/orders/:id/items/:item_id', action: 'remove', controller: 'orders'
  resources :providers
  resources :products
  put '/users/:id/make_admin', action: 'make_admin', controller: 'users'
  put '/users/:id/validate', action: 'validate', controller: 'users'
  put '/users/reset_validation', action: 'reset_validation', controller: 'users'
  resources :users
  root 'homepage#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  resourcify

  has_many :products, :dependent => :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include Utils

  before_action :authenticate_user!, except: %i[ show ]
  before_action :is_admin, except: %i[ show ]
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, html: {class: "form-admin"}) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-label-group">
    <%= form.label :name %><br />
    <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "form-control", required: true %>
  </div>

  <div class="actions">
    <%= form.submit(class: "btn btn-lg btn-primary btn-block") %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t :categories %></h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= t :name %></th>
      <th scope="col"><%= t :actions %></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %> | <%= link_to 'Edit', edit_category_path(category) %> | <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <div class="row">
    <div class="col-12">
      <h2><%= t :categories_information %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <label><%= t :name %></label>
    </div>
    <div class="col-6">
      <%= @category.name %>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>