config/routes.rb
Rails.application.routes.draw do
  resources :rounds
  resources :invoices
  get '/invoices/:id/download', action: 'download', controller: 'invoices', defaults: { format: :csv }
  resources :categories
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :cycles
  resources :orders
  put '/orders/:id/items', action: 'add', controller: 'orders'
  delete '/orders/:id/items/:item_id', action: 'remove', controller: 'orders'
  resources :providers
  resources :products
  put '/users/:id/make_admin', action: 'make_admin', controller: 'users'
  put '/users/:id/validate', action: 'validate', controller: 'users'
  put '/users/reset_validation', action: 'reset_validation', controller: 'users'
  resources :users
  root 'homepage#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  resourcify

  belongs_to :provider
  belongs_to :category
  has_many :conditionings, :dependent => :destroy

  accepts_nested_attributes_for :conditionings, allow_destroy: true, reject_if: :all_blank
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Utils

  before_action :authenticate_user!, except: %i[ show ]
  before_action :is_admin, except: %i[ show ]
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    if product_params[:conditionings_attributes].nil?
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    else
      respond_to do |format|
        if @product.save
          format.html { redirect_to @product, notice: "Product was successfully created." }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :unit, :min_quantity, :provider_id, :category_id, conditionings_attributes: [:id, :quantity, :unit, :price, :_destroy])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_conditioning_fields.html.erb
<div class="nested-fields row">
    <%= f.hidden_field :_destroy %>
    <div class="col-2">
        <%= f.text_field :cat_nb %>
    </div>
    <div class="col-2">
        <%= f.number_field :quantity %>
    </div>
    <div class="col-3">
      <%= f.select :unit, [[I18n.t(:grams), "g"], [I18n.t(:kilograms), "Kg"], [I18n.t(:liters), "l"], [I18n.t(:mililiters), "ml"]], {}, {:class => "custom-select d-block w-100"} %>
      <div class="invalid-feedback">
        <%= t :unit_not_valid %>
      </div>
    </div>
    <div class="col-2">
        <%= f.number_field :price, step: 0.01 %>
    </div>
    <div class="col-3">
        <%= link_to "Remove", '#', class: "remove_fields" %>
    </div>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, html: {class: "form-admin"}, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-label-group">
    <%= form.label :name %><br />
    <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "form-control", required: true %>
  </div>

  <div class="form-label-group">
    <%= form.label :provider %><br />
    <%= form.collection_select :provider_id, Provider.order(:name), :id, :name, {}, {:class => "custom-select d-block w-100"} %>
  </div>

  <div class="form-label-group">
    <%= form.label :category %><br />
    <%= form.collection_select :category_id, Category.order(:name), :id, :name, {}, {:class => "custom-select d-block w-100"} %>
  </div>

  <div class="form-label-group">
    <%= form.label :price %><br />
    <%= form.number_field :price, autofocus: true, autocomplete: "price", class: "form-control", required: true %>
  </div>

  <div class="form-label-group">
    <%= form.label :unit %><br />
    <%= form.select :unit, get_units_select(), {}, {:class => "custom-select d-block w-100"} %>
  </div>

  <div class="form-label-group">
    <%= form.label :min_quantity %><br />
    <%= form.number_field :min_quantity, autofocus: true, autocomplete: "price", class: "form-control", required: true %>
  </div>

  <fieldset>
    <legend><%= t :conditionings %>:</legend>
    <div class="row">
      <div class="col-2">
        <%= t :cat_nb %>
      </div>
      <div class="col-2">
        <%= t :quantity %>
      </div>
      <div class="col-3">
        <%= t :unit %>
      </div>
      <div class="col-2">
        <%= t :price %>
      </div>
      <div class="col-3">
        <%= t :action %>
      </div>
    </div>
    <%= form.fields_for :conditionings do |conditionings_form| %>
      <%= render "conditioning_fields", f: conditionings_form %>
    <% end %>
    <%= link_to_add_fields "Add conditioning", form, :conditionings %>
  </fieldset>

  <div class="actions">
    <%= form.submit(class: "btn btn-lg btn-primary btn-block") %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1><%= t :editing_product %></h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t :products %></h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= t :name %></th>
      <th scope="col"><%= t :provider %></th>
      <th scope="col"><%= t :price %></th>
      <th scope="col"><%= t :min_quantity %></th>
      <th scope="col"><%= t :actions %></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.provider.name %></td>
        <td><%= product.price %> <%= t :per %> <%= product.unit %></td>
        <td><%= product.min_quantity %> <%= product.unit %></td>
        <td><%= link_to 'Show', product %> | <%= link_to 'Edit', edit_product_path(product) %> | <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-12">
      <h2><%= t :product_information %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <label><%= t :name %></label>
    </div>
    <div class="col-6">
      <%= @product.name %>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <label><%= t :provider %></label>
    </div>
    <div class="col-6">
      <%= @product.provider.name %>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <label><%= t :price %></label>
    </div>
    <div class="col-6">
      <%= @product.price %> <%= t :currency %> per <%= @product.unit %>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <label><%= t :min_quantity %></label>
    </div>
    <div class="col-6">
      <%= @product.min_quantity %> <%= @product.unit %>
    </div>
  </div>
</div>

<% if @product.conditionings.count == 0 %>
  <div class="row">
    <div class="col-12 text-center">
      <h2 class="text-danger"><%= t :please_add_conditioning_error %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-12 text-center">
      <a class="btn btn-danger" href=<%= "/products/" + @product.id.to_s + "/edit"%>><%= t :add %></a>
    </div>
  </div>
<% end %>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col"><%= t :price %></td>
      <th scope="col"><%= t :quantity %></td>
      <th scope="col"><%= t :unit %></td>
    </tr>
  </thead>
  <tbody>
  <% @product.conditionings.each do |conditioning| %>
    <tr>
      <td><%= conditioning.price %></td>
      <td><%= conditioning.quantity %></td>
      <td><%= conditioning.unit %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>